### PR TITLE
SQKCoreDataOperation only saves and merges the private context it created.

### PR DESCRIPTION
**Pull request by lukestringer90**
Addressing #6 

BUG: After adding this test the tests suite hangs during the 
[`[SQKManagedObjectControllerTests testInitialisingWithObjectAsync]`](https://github.com/3squared/SQKDataKit/blob/824a1a125b1ab5b4fb0f14570caa005cbf18dafd/Project/SQKDataKitTests/SQKManagedObjectControllerTests.m#L254) test on the [`[_mainContext mergeChangesFromContextDidSaveNotification:notification]`](https://github.com/3squared/SQKDataKit/blob/824a1a125b1ab5b4fb0f14570caa005cbf18dafd/Classes/shared/Core/SQKContextManager.m#L81) call in SQKContextManager.

See [travis build](https://travis-ci.org/3squared/SQKDataKit/builds/34169306#L475).

### CODE REVIEW

**Comment by blork** [comment]
This doesn't fix #6, it just tests it, right? In what commit was the fix applied?

**Comment by lukestringer90** [comment]
Rebased onto master and the test still hangs in the same way. 

I'm tempted to just delete the test to be honest as it's only testing a single [if branch](https://github.com/3squared/SQKDataKit/blob/a820817dbb66165d14aa71dc0a57d21b6a326eef/Classes/shared/SQKCoreDataOperation/SQKCoreDataOperation.m#L137), although I would like to try and narrow down why the tests hangs first.

**Comment by blork** [comment]
@lukestringer90 Any progress on this? Appears to be the last remaining thing before 0.6.0 can be released.

**Comment by lukestringer90** [comment]
@blork No progress no. I have a feeling that this issue can only be observed when running the test suite and should not occur in production code. Might come back to bite me, but my decision is detailed here.

**Pull request closed without merging**
