### PR TITLE
Bump version number (1.1.0)

### PR DESCRIPTION
**Pull request by CaptainRedmuff**
Bump version number of Xcode project and podspec

### CODE REVIEW

**Comment by steprescott** [comment]
Need to update the README too.

**Comment by CaptainRedmuff** [comment]
Do you mean to include documentation for the new method added here? https://github.com/3squared/SQKDataKit/pull/74

**Comment by steprescott** [comment]
That too :-)

**Comment by CaptainRedmuff** [comment]
What changes to the README need to be made then?

**Comment by steprescott** [comment]
Your pod version number & new method docs. The version number will automatically update once you push your latest podspec to CocoaPods' trunk.

**Pull request merged**
